name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build the JAR file
      - name: Build JAR
        run: mvn clean package

      # List files in target directory to ensure JAR is present
      - name: List files in target directory
        run: |
         ls -l target/

      # Log in to Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t tshrey/shreyaswebsite:latest .

      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push tshrey/shreyaswebsite:latest

      # Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Pull the Docker image (no need to login since it's public)
            docker pull tshrey/shreyaswebsite:latest || true
            docker stop shreyaswebsite || true
            docker rm shreyaswebsite || true
            docker run -d -p 8080:8080 --name shreyaswebsite tshrey/shreyaswebsite:latest
