name: Generate Keystore JKS

on:
  workflow_dispatch:

jobs:
  generate-and-commit-jks:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Generate the self-signed keystore (JKS file)
      - name: Generate Keystore JKS
        run: |
          mkdir -p src/main/resources
          keytool -genkeypair -v -keystore src/main/resources/keystore.jks -keyalg RSA -keysize 2048 -validity 3650 -alias selfsigned -dname "CN=ShreyasCert, OU=Dev, O=MyOrg, L=City, ST=State, C=US" -storepass DummyPassword123 -keypass DummyPassword123

      # Commit the generated JKS file to the repository
      - name: Commit JKS file to repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add src/main/resources/keystore.jks
          git commit -m "Add generated keystore.jks"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
